### PR TITLE
add equalizer project

### PR DESCRIPTION
**Pull request by Bloomca**
Web audio player with equalizer. Actually, [readme](https://github.com/Bloomca/equalizer/blob/master/README.md) and the [app](http://bloomca.github.io/equalizer/) itself are better than any explanations.

Thanks,
Seva

### CODE REVIEW

**Comment by Widdershin** [comment]
Thanks for adding this! 😄

**Comment by Widdershin** [comment]
And it's live now: https://cyclejs-community.github.io/built-with-cycle/

**Comment by Widdershin** [comment]
I've also invited you to be a part of our community, which means you can make and transfer repos into this organization for more visibility/collaboration.

As part of our [community values](https://github.com/cyclejs-community/cyclejs-community), having a PR merged also means you are welcome to join the repo as a contributor:

> When one of your pull requests is merged, you will be added as a collaborator to the repository. This allows for easier collaboration (as collaborators can work together on pull requests).
> 
> Being a collaborator means:
> - You can push to the repo, and to branches.
> - With the permission of the other collaborators, you can merge pull requests.
> - You get to have a say in the development of the project.
> - You have no obligation to contribute, but any work you do is very appreciated.
> - You still work with pull requests, but now you work on the repo itself, not your fork. This makes it easier to collaborate.

**Comment by Bloomca** [comment]
@Widdershin yeah, thank you very much!

Will try to know more about the whole ecosystem and to contribute to some projects.

**Comment by Widdershin** [comment]
Great. If you have any questions, please feel free to ask here 😸

**Pull request merged**
