### PR TITLE
Pull master into gh-pages

### PR DESCRIPTION
**Pull request by artfuldev**

### CODE REVIEW

**Comment by artfuldev** [comment]
@Widdershin what am I doing wrong here? The page doesn't seem to be updated?

**Comment by Widdershin** [comment]
@artfuldev just run the `scripts/deploy` script locally, it will update gh-pages

**Comment by artfuldev** [comment]
@Widdershin Could you do that? The latest project never got added :(

**Comment by artfuldev** [comment]
@Widdershin hmmm, getting a lot of errors on my windows machine. Could you do it please?

**Pull request merged**
