### PR TITLE
Add meeting-price-calculator

### PR DESCRIPTION
**Pull request by olpeh**

### CODE REVIEW

**Comment by artfuldev** [comment]
Thanks!

**Comment by artfuldev** [comment]
@Widdershin @Bloomca sorry, didn't see that review request

**Comment by artfuldev** [comment]
https://github.com/cyclejs-community/built-with-cycle/tree/revert-18-master will let us revert if needed

**Comment by Widdershin** [comment]
Deployed 😄

**Comment by olpeh** [comment]
Thanks :)

**Pull request merged**
